# Generated by Django 3.1.4 on 2020-12-04 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='disabled_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2bea0961-1ddf-45e3-b4af-df22bb69c3c9'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e60d5b49-fce5-451f-a591-71a45fced7dd'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d136e775-73b4-444b-af53-f491ab6496e5'), primary_key=True, serialize=False, unique=True)),
                ('deposited_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('reference_id', models.UUIDField()),
                ('deposited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='app.wallet')),
            ],
        ),
    ]
