# Generated by Django 3.1.4 on 2020-12-04 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201204_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f49cbe4-0d7e-41b5-a070-ca654eba2b64'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a74d7751-493e-4513-a9d3-823f3c4c4c2a'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='disabled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='enabled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3aa91202-5186-485d-a7bb-0f010456c06b'), primary_key=True, serialize=False, unique=True),
        ),
    ]
