# Generated by Django 3.1.4 on 2020-12-04 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201204_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0597ffb7-6645-4c96-be4d-2483ff997708'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a10f709-f83d-43f2-8d6b-5192347497ee'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b22aa89e-6ec7-4b63-93ad-f24558187ca0'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7093d934-f00f-46e1-b604-151ad40fe19f'), primary_key=True, serialize=False, unique=True)),
                ('withdrawn_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('reference_id', models.UUIDField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wallet')),
                ('withdrawn_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
